ARG CHART_DEFAULT_BRANCH=dev-v2.11
ARG PARTNER_CHART_DEFAULT_BRANCH=main
ARG RKE2_CHART_DEFAULT_BRANCH=main

FROM registry.suse.com/bci/bci-base:15.6 AS tools
RUN zypper refresh && zypper -n install git

FROM tools AS charts
ARG CHART_DEFAULT_BRANCH
RUN mkdir -p /var/lib/rancher-data/local-catalogs/v2 && \
    git config --global url."https://github.com/rancher/".insteadOf https://git.rancher.io/ && \
    git clone --no-checkout -b $CHART_DEFAULT_BRANCH --depth 1 https://git.rancher.io/charts /var/lib/rancher-data/local-catalogs/v2/rancher-charts/4b40cac650031b74776e87c1a726b0484d0877c3ec137da0872547ff9b73a721

FROM tools AS partner-charts
ARG PARTNER_CHART_DEFAULT_BRANCH
RUN mkdir -p /var/lib/rancher-data/local-catalogs/v2 && \
    git config --global url."https://github.com/rancher/".insteadOf https://git.rancher.io/ && \
    git clone --no-checkout -b $PARTNER_CHART_DEFAULT_BRANCH --depth 1 https://git.rancher.io/partner-charts /var/lib/rancher-data/local-catalogs/v2/rancher-partner-charts/8f17acdce9bffd6e05a58a3798840e408c4ea71783381ecd2e9af30baad65974

FROM tools AS rke2-charts
ARG RKE2_CHART_DEFAULT_BRANCH
RUN mkdir -p /var/lib/rancher-data/local-catalogs/v2 && \
    git config --global url."https://github.com/rancher/".insteadOf https://git.rancher.io/ && \
    git clone --no-checkout -b $RKE2_CHART_DEFAULT_BRANCH --depth 1 https://git.rancher.io/rke2-charts /var/lib/rancher-data/local-catalogs/v2/rancher-rke2-charts/675f1b63a0a83905972dcab2794479ed599a6f41b86cd6193d69472d0fa889c9

FROM tools AS tini
ARG TARGETARCH
ENV TINI_VERSION=v0.18.0
ENV TINI_URL_amd64=https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini \
    TINI_URL_arm64=https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-arm64 \
    TINI_URL_s390x=https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-s390x \
    TINI_URL=TINI_URL_${TARGETARCH}
RUN curl -sLf ${!TINI_URL} > /usr/bin/tini && \
    chmod +x /usr/bin/tini

FROM tools AS etcd
ARG TARGETARCH
ENV CATTLE_ETCD_VERSION=v3.5.16
ENV ETCD_URL=https://github.com/etcd-io/etcd/releases/download/${CATTLE_ETCD_VERSION}/etcd-${CATTLE_ETCD_VERSION}-linux-${TARGETARCH}.tar.gz
RUN mkdir -p /etcd && curl -sfL ${ETCD_URL} | tar xvzf - --strip-components=1 --no-same-owner -C /etcd etcd-${CATTLE_ETCD_VERSION}-linux-${TARGETARCH}/etcdctl

# The final image
FROM registry.suse.com/bci/bci-base:15.6

ARG CHART_DEFAULT_BRANCH
ARG PARTNER_CHART_DEFAULT_BRANCH
ARG RKE2_CHART_DEFAULT_BRANCH

ENV CATTLE_CHART_DEFAULT_BRANCH=$CHART_DEFAULT_BRANCH
ENV CATTLE_PARTNER_CHART_DEFAULT_BRANCH=$PARTNER_CHART_DEFAULT_BRANCH
ENV CATTLE_RKE2_CHART_DEFAULT_BRANCH=$RKE2_CHART_DEFAULT_BRANCH

RUN mkdir -p /var/lib/rancher/k3s/agent/images/ && \
    mkdir -p /var/lib/rancher-data/driver-metadata

COPY --from=etcd /etcd/* /usr/bin/
COPY --from=charts /var/lib/rancher-data/local-catalogs/v2/rancher-charts/4b40cac650031b74776e87c1a726b0484d0877c3ec137da0872547ff9b73a721 /var/lib/rancher-data/local-catalogs/v2/rancher-charts/4b40cac650031b74776e87c1a726b0484d0877c3ec137da0872547ff9b73a721
COPY --from=partner-charts /var/lib/rancher-data/local-catalogs/v2/rancher-partner-charts/8f17acdce9bffd6e05a58a3798840e408c4ea71783381ecd2e9af30baad65974 /var/lib/rancher-data/local-catalogs/v2/rancher-partner-charts/8f17acdce9bffd6e05a58a3798840e408c4ea71783381ecd2e9af30baad65974
COPY --from=rke2-charts /var/lib/rancher-data/local-catalogs/v2/rancher-rke2-charts/675f1b63a0a83905972dcab2794479ed599a6f41b86cd6193d69472d0fa889c9 /var/lib/rancher-data/local-catalogs/v2/rancher-rke2-charts/675f1b63a0a83905972dcab2794479ed599a6f41b86cd6193d69472d0fa889c9
COPY --from=tini /usr/bin/tini /usr/bin/tini
