ARG IMAGE=server

# For subset of Rancher
FROM ${IMAGE} as rancher

FROM registry.suse.com/bci/bci-base:15.6
COPY --from=rancher /var/lib/rancher-data /var/lib/rancher-data
COPY --from=rancher /usr/bin/tini /usr/bin/
RUN echo "Faking go build of server binary" && sleep 5
